#include "stm32f4xx_hal.h"

// Function prototypes
void SystemClock_Config(void);
static void GPIO_Init(void);

int main(void)
{
    HAL_Init();              // Initialize HAL Library
    SystemClock_Config();    // Configure system clock
    GPIO_Init();             // Initialize GPIO

    while (1)
    {
        HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5); // Toggle LED pin
        HAL_Delay(500); // Delay 500 ms
    }
}

// GPIO Initialization
static void GPIO_Init(void)
{
    __HAL_RCC_GPIOA_CLK_ENABLE(); // Enable GPIOA clock

    GPIO_InitTypeDef GPIO_InitStruct = {0};

    GPIO_InitStruct.Pin = GPIO_PIN_5;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP; // Push-pull output
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;

    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
}

// System Clock Configuration (basic template)
void SystemClock_Config(void)
{
    // This is a minimal placeholder
    // Normally generated by STM32CubeMX
}
